package com.aarhankhan.juitattendanceapi.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Attendance")
public class Attendance {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String attendanceId;

    @DynamoDBAutoGeneratedTimestamp
    private String dateTime;

    @DynamoDBAttribute
    private Student student;

    @DynamoDBAttribute
    private Subject subject;


}
