package com.aarhankhan.juitattendanceapi.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Subject")
public class Subject {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String subjectId;

    @DynamoDBAutoGeneratedTimestamp
    private String timeStamp;

    @DynamoDBAttribute
    private String subjectCode;

    @DynamoDBAttribute
    private String subjectName;

    @DynamoDBAttribute
    private String startTime;

    @DynamoDBAttribute
    private String endTime;

    @DynamoDBAttribute
    private String subjectSemester;

    @DynamoDBAttribute
    private String subjectType;

    @DynamoDBAttribute
    private String subjectStrength;

    @DynamoDBAttribute
    private String subjectTeacher;
}
